### PR TITLE
cleanup add-build-tags

### PR DESCRIPTION
**Pull request by eliranmal**
- make the contents of the build-file param a cdata section, and replace escaped entities with their corresponding characters, for ease of maintenance and better readability.

- send plain text instead of xml to teamcity server (and expect 200 status instead of 204).

### CODE REVIEW

**Comment by pavelsher** [comment]
I'd say it would be better to continue asking for username and password. At least for audit purposes. Also in some setups build does not have permissions to set tags.

**Comment by eliranmal** [comment]
@pavelsher - thanx for reviewing!

in my case, asking for user/password would force me to feed the credentials of our dedicated CI user (which is already available through `teamcity.auth...`), while my own user's credentials didn't work (only the CI user have the proper credentials to use the teamcity server API).

would you say this is the common case (that was my thought when i removed the prompt for credentials)?

if not, and each system is set up quite differently (in terms of credentials), it definitely seems reasonable to still prompt for credentials, and i will put these back.

**Comment by pavelsher** [comment]
On the majority of installations build has enough permissions to set tags. But this won't always be the case, we have plans to reduce build permissions. So this is why I don't like removing of the username / password completely.

One more option is to add checkbox whether to use build own authentication or username and password. Checkbox could be turned on by default.

**Comment by eliranmal** [comment]
@pavelsher - the checkbox idea is great! i'll try and implement that and push the changes.

**Comment by eliranmal** [comment]
i cleaned up this PR, and ended up taking a little different approach to the credentials issue - see this PR.

**Pull request merged**
