### PR TITLE
Add option to specify AssemblyInfo file name for GitVersion

### PR DESCRIPTION
**Pull request by gusztavvargadr**
Add support for specifying custom AssemblyInfo file name as described at http://gitversion.readthedocs.org/en/latest/usage/command-line/#inject-version-metadata-into-the-assembly.

### CODE REVIEW

**Comment by pavelsher** [comment]
TeamCity has a build feature which is called: Aseembly Info patcher (https://confluence.jetbrains.com/display/TCD9/AssemblyInfo+Patcher). This build feature can change version in various AssemblyInfo.cs files. There can be plenty of them: AssemblyInfo.css, AssemblyInfo .vb, GlobalAssemblyInfo.cs, etc.

Isn't it better to use this build feature instead?

**Comment by caioproiete** [comment]
@pavelsher: The Assembly Info Patcher build feature runs before the meta-runner had the chance to modify the build.number in TeamCity, so it is not possible to use it.

If there was any way of delaying when the build feature runs (or manually call it via a step), then it would work.

**Comment by gep13** [comment]
While the assembly info patcher build step will work, this PR seems to add support for the ability of GitVersion to update a specific, common, assembly info file.  This functionality was excluded from the original GitVersion Meta Runner submission, likely because of a documentation error in GitVersion.  If you are happy to include the GitVersion metarunner in this repository, then I think this PR should be included to provide all the available functionality of GitVersion.

**Comment by gusztavvargadr** [comment]
@pavelsher, @caioproiete, @gep13, thanks for all the comments!

Indeed, the main intent was just to support the parameters GitVersion itself already has.

Even if it's possible to have it implemented with other already existing tooling, this way we can have our processes outside the context of TeamCity closer to what we have in a build configuration.

Also, as GitVersion supports also [formatting](http://gitversion.readthedocs.org/en/latest/configuration/#global-configuration) the various assembly version numbers in its own configuration too, the new parameter in this PR prevents duplicating this setup and maintaining it in both places.

**Comment by pavelsher** [comment]
Thank you for all your comments! Accepted the patch.

**Comment by gep13** [comment]
@pavelsher thank you! :+1:

**Comment by gusztavvargadr** [comment]
@pavelsher thanks!

**Pull request merged**
