### PR TITLE
Add meta runner for GitVersion 3

### PR DESCRIPTION
**Pull request by eggapauli**

### CODE REVIEW

**Comment by pavelsher** [comment]
Could you please describe what is the difference between this meta runner and another one which we already have: https://github.com/JetBrains/meta-runner-power-pack/tree/master/gitversion ?

**Comment by gep13** [comment]
@pavelsher GitVersion Version 3 is currently in beta.  There have been quite a few changes to the way that it works from Version 2, in terms of how it is configued.  It should be backwards compatible, but I can understand that it might be desirable to have two meta runners.

@robdmoore what are your thoughts on this?

**Comment by eggapauli** [comment]
To continue on @gep13's comment, there are new switches for GitVersion 3 that version 2 won't understand (it may even fail if you throw them at v2). Since v3 is still in beta, I thought it's good to not overwrite the meta runner for v2, but I'm not sure what your policy on this is.

**Comment by robdmoore** [comment]
Given the meta runner is a single file it's pretty easy to put 2 and 3 side-by-side and name the files appropriately?

**Comment by eggapauli** [comment]
Sorry, but isn't that what I did? I added "MR_GitVersion3.xml" besides "MR_GitVersion.xml".

**Comment by robdmoore** [comment]
So you did :P I didn't look at the diff sorry :)

**Comment by eggapauli** [comment]
Never mind :-)

**Comment by gep13** [comment]
For what it is worth, this gets my vote :+1:

**Pull request merged**
